import moment = require('moment');
import { GuidNoDash } from '../utils/generateGuid';

export const acctRqst = (login: string, passwd: string) => {
  return `OFXHEADER:100
DATA:OFXSGML
VERSION:102
SECURITY:NONE
ENCODING:USASCII
CHARSET:1252
COMPRESSION:NONE
OLDFILEUID:NONE
NEWFILEUID:${GuidNoDash()}

<OFX>
<SIGNONMSGSRQV1>
<SONRQ>
<DTCLIENT>${moment().format('YYYYMMDDhhmmss')}
<USERID>${login}
<USERPASS>${passwd}<LANGUAGE>ENG
<FI>
<ORG>B1
<FID>10898
</FI>
<APPID>QWIN
<APPVER>1800
<CLIENTUID>INSERT CLIENT UID HERE
</SONRQ>
</SIGNONMSGSRQV1>
<SIGNUPMSGSRQV1>
<ACCTINFOTRNRQ>
<TRNUID>${GuidNoDash()}
<CLTCOOKIE>4
<ACCTINFORQ>
<DTACCTUP>19700101000000
</ACCTINFORQ>
</ACCTINFOTRNRQ>
</SIGNUPMSGSRQV1>
</OFX>`;
};

export const ccStatsRqst = (login: string, passwd: string, acct: string, months: number = 12) => {
  return `OFXHEADER:100
DATA:OFXSGML
VERSION:102
SECURITY:NONE
ENCODING:USASCII
CHARSET:1252
COMPRESSION:NONE
OLDFILEUID:NONE
NEWFILEUID:${GuidNoDash()}

<OFX>
<SIGNONMSGSRQV1>
<SONRQ>
<DTCLIENT>${moment().format('YYYYMMDDhhmmss')}
<USERID>${login}
<USERPASS>${passwd}<LANGUAGE>ENG
<FI>
<ORG>B1
<FID>10898
</FI>
<APPID>QWIN
<APPVER>1800
<CLIENTUID>INSERT CLIENT UID HERE
</SONRQ>
</SIGNONMSGSRQV1>
<CREDITCARDMSGSRQV1>
<CCSTMTTRNRQ>
<TRNUID>${GuidNoDash()}
<CLTCOOKIE>4
<CCSTMTRQ>
<CCACCTFROM>
<ACCTID>${acct}
</CCACCTFROM>
<INCTRAN>
<DTSTART>${moment()
    .subtract(months, 'month')
    .format('YYYYMMDD')}
<INCLUDE>Y
</INCTRAN>
</CCSTMTRQ>
</CCSTMTTRNRQ>
</CREDITCARDMSGSRQV1>
</OFX>`;
};

export const bankStatsRqst = (login: string, passwd: string, acct: string, months: number = 12) => {
  return `OFXHEADER:100
DATA:OFXSGML
VERSION:102
SECURITY:NONE
ENCODING:USASCII
CHARSET:1252
COMPRESSION:NONE
OLDFILEUID:NONE
NEWFILEUID:${GuidNoDash()}

<OFX>
<SIGNONMSGSRQV1>
<SONRQ>
<DTCLIENT>${moment().format('YYYYMMDDhhmmss')}
<USERID>${login}
<USERPASS>${passwd}<LANGUAGE>ENG
<FI>
<ORG>B1
<FID>10898
</FI>
<APPID>QWIN
<APPVER>1800
<CLIENTUID>INSERT CLIENT UID HERE
</SONRQ>
</SIGNONMSGSRQV1>
<BANKMSGSRQV1>
<STMTTRNRQ>
<TRNUID>${GuidNoDash()}
<CLTCOOKIE>4
<STMTRQ>
<BANKACCTFROM>
<BANKID>071000013
<ACCTID>${acct}
<ACCTTYPE>CHECKING
</BANKACCTFROM>
<INCTRAN>
<DTSTART>${moment()
    .subtract(months, 'month')
    .format('YYYYMMDD')}
<INCLUDE>Y
</INCTRAN>
</STMTRQ>
</STMTTRNRQ>
</BANKMSGSRQV1>
</OFX>`;
};
